### ISSUE TITLE
Send campaign test cases

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#1042]

**Comment by Dzalevski** [comment]
1. Test Send Email Metadata/Default Metadata
 - Status:
2. Test Clicks After Send email.
 - Status:
3. Test Bounces After Send email.
 - Status:
4. Test Deliveries After Send email.
 - Status:
5. Test Complaints After Send email.
 - Status:
6. Test Opens After Send Email.
 - Status:
7. Test Campaigner Idempotency.
 - Status:
8. Test Sender Idempotency.
 - Status:
9. Test Campaign segments with subscriber in two segments.
- Status:
10. Test Email simulator with big data.
- Status:

**Comment by gudgl** [comment]
# Test 1 
### Template
#### subject_part
```
Welcome {{name}}
```
#### text_part
```
{{header}}

Dear {{name}}, 

You have subscribed to our newsletter.

Facebook {{fb_link}}
Instagram {{i_link}}
Twitter {{t_link}}

Unsubscribe => {{unsubscribe_url}}
```
#### html_part
```
<h1>{{header}}</h1>

Dear {{name}}, 

You have subscribed to our newsletter.

<ul>
    <li>Facebook {{fb_link}}<li>
    <li>Instagram {{i_link}}<li>
    <li>Twitter {{t_link}}<li>
<ul>



<a href="{{unsubscribe_url}}"><button>Unsubscribe</buntton></a>
```
### Sent to two segments
#### segment 1
- dare_zalevski@yahoo.com
- bounce@simulator.amazonses.com
#### segment 2
- glgudjevski@gmail.com
- dare_zalevski@yahoo.com

## After starting campaign
### Send logs
- glgudjevski@gmail.com :heavy_check_mark:
- dare_zalevski@yahoo.com :heavy_check_mark:
- bounce@simulator.amazonses.com :heavy_check_mark:
### Sends
- glgudjevski@gmail.com :heavy_check_mark:
- dare_zalevski@yahoo.com :heavy_check_mark:
- bounce@simulator.amazonses.com :heavy_check_mark:
### Deiveries
- glgudjevski@gmail.com :heavy_check_mark:
- dare_zalevski@yahoo.com :x: he complained last time we tested
- bounce@simulator.amazonses.com :x: bounced email
### Bounces
- bounce@simulator.amazonses.com :heavy_check_mark:
### Opens
- glgudjevski@gmail.com :heavy_check_mark:
### Complaints 
- dare_zalevski@yahoo.com :heavy_check_mark: (empty `type` and `user_agent`)
### Clicks
- glgudjevski@gmail.com :x: clicked all links several times but nothing

**Comment by gudgl** [comment]
# Test 2
### Template
#### subject_part
```
Welcome {{name}}
```
#### text_part
```
{{header}}

Dear {{name}}, 

You have subscribed to our newsletter.

Facebook {{fb_link}}
Instagram {{i_link}}
Twitter {{t_link}}

Unsubscribe => {{unsubscribe_url}}
```
#### html_part
```
<h1>{{header}}</h1>

Dear {{name}}, 

You have subscribed to our newsletter.

<ul>
    <li>Facebook {{fb_link}}<li>
    <li>Instagram {{i_link}}<li>
    <li>Twitter {{t_link}}<li>
<ul>



<a href="{{unsubscribe_url}}"><button>Unsubscribe</buntton></a>
```
### Sent to two segments
#### segment 1
- dare_zalevski2@yahoo.com
- bounce@simulator.amazonses.com
#### segment 2
- glgudjevski1@gmail.com
- dare_zalevski2@yahoo.com

## After starting campaign
### Send logs
- glgudjevski1@gmail.com :heavy_check_mark: with status failed
- dare_zalevski2@yahoo.com :heavy_check_mark: with status failed
- bounce@simulator.amazonses.com :x:
### Sends
- glgudjevski1@gmail.com :x:
- dare_zalevski2@yahoo.com :x:
- bounce@simulator.amazonses.com :x:
### Deiveries
- glgudjevski@gmail.com :x:
- dare_zalevski@yahoo.com :x:
- bounce@simulator.amazonses.com :x:
### Bounces
- bounce@simulator.amazonses.com :x:

## Campaigner idempotency (we published the same message twice) :heavy_check_mark: 
- There was log that this campaign is with status `sending`
## Sender idempotency (we published all mails twice) :heavy_check_mark: 
- There was log that message has already been processed

**Comment by gudgl** [comment]
# Test 2
### Template
#### subject_part
```
Welcome {{name}}
```
#### text_part
```
{{header}}

Dear {{name}}, 

You have subscribed to our newsletter.

Facebook {{fb_link}}
Instagram {{i_link}}
Twitter {{t_link}}

Unsubscribe => {{unsubscribe_url}}
```
#### html_part
```
<h1>{{header}}</h1>

Dear {{name}}, 

You have subscribed to our newsletter.

<ul>
    <li>Facebook {{fb_link}}<li>
    <li>Instagram {{i_link}}<li>
    <li>Twitter {{t_link}}<li>
<ul>



<a href="{{unsubscribe_url}}"><button>Unsubscribe</buntton></a>
```
### Sent to one segment
- 58.3K subscrubers

### This took `35912ms`
