### ISSUE TITLE
Unsubscribed users event history

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#1066]
**Is your feature request related to a problem? Please describe.**
We should have a record of each user that has unsubscribed. Currently, we just set the `active` field to false, when a user unsubscribes.

**Comment by Dzalevski** [comment]
Hmm should we make new table `unsubscribed_subscribers` and set active to 0, insert into `unsubscribed_subscribers` on unsunbscribe.
 @FilipNikolovski 
| id  | email | created_at |
| ------------- | ------------- | ------------- |
| 1  | bla@email.com  | 123125135

**Comment by FilipNikolovski** [comment]
I agree, we can always add more columns later on if we need to, let's just do the basic functionality for now.
