### ISSUE TITLE
Implement campaign logs

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#1096]
When sending a campaign, the user will have no visibility when the campaigner consumer fails to send the campaign successfully. We'll need to implement an immutable log of events for each campaign that is being sent.

**Comment by Dzalevski** [comment]
MySQL database table: `campaign_failed_logs`
| id  | user_id| campaign_id | reason | error | created_at |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 1  | 1  | 1 | Campaign failed | the acctual error | 1232131312 |
@gudgl @FilipNikolovski

**Comment by FilipNikolovski** [comment]
When we decide to show the failed logs, we'll need to take into account that we should **not show** the actual error, which is only for internal purposes.
