### ISSUE TITLE
Bug: Reading from stream(io.Reader) two times

### ISSUE THREAD

**Issue by Dzalevski** [mailbadger/app#1122]
With current implementation in Import Subscribers we are reading from  the stream (io.Reader) two times, second read will be empty stream.
1. CheckLines with limit func
2. The actual read in import svc.

**Comment by FilipNikolovski** [comment]
We can create a new reader from the same bytes and pass it along. Here's an example: https://siongui.github.io/2018/10/28/go-read-twice-from-same-io-reader/
