### ISSUE TITLE
Bug: PutSegment and DetachSegmentSubscribers actions 

### ISSUE THREAD

**Issue by gudgl** [mailbadger/app#1127]
##PutSegment
The action should update the segments name. The result is success but the name is not updated.

##DetachSegmentSubscribers
This actions Detaches subscribers from a segment. Its DELETE method and receives the subscriber ids in the body. Unfortunately
this is not possible DELETE methods body is not sent to the server.

**Comment by FilipNikolovski** [comment]
Doesn't DetachSegmentSubscribers remove all subscribers from a segment?

**Comment by gudgl** [comment]
As i can see in the code it tries to send subscriber ids in the body and then it detaches those subscribers.

**Comment by gudgl** [comment]
since you merged the changes i am closing this issue
