### ISSUE TITLE
Discussion: Boundaries type

### ISSUE THREAD

**Issue by gudgl** [mailbadger/app#1128]
All boundaries have type shouldn't we checking the type. For example there is `nolimit` type

![image](https://user-images.githubusercontent.com/35736870/110871199-3b052980-82ce-11eb-81df-a793b85c3b1a.png)

Does this means that there is no limit for that user

**Comment by FilipNikolovski** [comment]
The types are just so we identify what kind of a boundary the user has. We should explicitly check the limits and we should not rely on the `type`. If a user has a 0 limit for a resource, it means that he can have **unlimited** number of that resource.

**Comment by gudgl** [comment]
So we should only check the limit value.

**Comment by FilipNikolovski** [comment]
Yes the type is irrelevant when performing the checks.
