### ISSUE TITLE
Campaigns stats endpoint

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#52]
After the campaign is sent, we would want to see a report for our campaign. The report would have a total number of:

- sends
- deliveries
- opens
- clicks
-  bounces
- complaints

This would be presented in the campaign's report component as a bar chart and also a percentage component, like:
![campaigns-report-bar-chart](https://user-images.githubusercontent.com/4439036/91223592-280b7d00-e721-11ea-8b7b-516179bac401.png)
![campaigns-report-percentages](https://user-images.githubusercontent.com/4439036/91224148-f5ae4f80-e721-11ea-95df-87efa75d7a35.png)

API endpoint:

**GET /api/campaigns/{id}/stats**

Response object
```json
{
  "recipients": 10000,
  "total_sent": 10000,
  "delivered": 5000,
  "opens": {
    "unique": 52,
    "total": 102
  },
  "clicks": {
    "unique": 25,
    "total": 32
  },
  "bounces": 456,
  "complaints": 128
}
```

**Comment by Dzalevski** [comment]
@FilipNikolovski How should i count   "recipients": 10000 ?

**Comment by FilipNikolovski** [comment]
@Dzalevski That's a good question :D we currently do not store the segments that the user has chosen to send. That's the only way to count them. For now, leave the recipients out of the response, we'll figure something out.

**Comment by Dzalevski** [comment]
@FilipNikolovski 'Clicks' Analytics it's for all links? or we should add which link?

**Comment by Dzalevski** [comment]
Spent 4h Today on this issue
