### ISSUE TITLE
Request input binding and validation

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#522]
We'll need to add user input validation on all of our action endpoints in a standardized way.

Use gin's model binding and validation as described here: https://github.com/gin-gonic/gin#model-binding-and-validation

**Comment by Dzalevski** [comment]
binding: required
post template with missing subject and name params error type :
ERRO[0003] Unable to bind post template params.          error="Key: 'postTemplate.Name' Error:Field validation for 'Name' failed on the 'required' tag\nKey: 'postTemplate.Subject' Error:Field validation for 'Subject' failed on the 'required' tag" request_id=1a62cf82-4503-4971-be3b-fcfd96897213 user_id=1

**Comment by Dzalevski** [comment]
binding: max=3(chars number) 
sending more then 3chars for a name(param) on post template, error type:
`ERRO[0112] Error #01: Key: 'postTemplate.Name' Error:Field validation for 'Name' failed on the 'max' tag  fields.time="2020-09-18T11:52:33Z" ip=127.0.0.1 latency=6.203611ms method=POST path=/api/templates status=422 user-agent=insomnia/2020.3.3
`

**Comment by Dzalevski** [comment]
PostTemplate param: content binding:"required,html"
sending not html on content error type:
`ERRO[0014] Error #01: Key: 'postTemplate.Html' Error:Field validation for 'Html' failed on the 'html' tag  fields.time="2020-09-18T11:55:05Z" ip=127.0.0.1 latency=6.503582ms method=POST path=/api/templates status=422 user-agent=insomnia/2020.3.3
`

**Comment by Dzalevski** [comment]
@FilipNikolovski Should we return the error message from binding pkg? Because binding pkg is returning the actual error.

**Comment by Dzalevski** [comment]
@FilipNikolovski Message is not really user friendly 😄

**Comment by Dzalevski** [comment]
1h spent today on this issue. with @Gligor23

**Comment by FilipNikolovski** [comment]
@Dzalevski for a more user friendly validation we should try a solution like this:

```go
if err := c.ShouldBind(&params); err != nil {
	for _, fieldErr := range err.(validator.ValidationErrors) {
		c.JSON(http.StatusBadRequest, fmt.Sprint(fieldErr))
		return // exit on first error
	}
}
```

Something along those lines, also every string should have a max length of 191.

**Comment by Dzalevski** [comment]
@FilipNikolovski okay we will re-test this, upload docs later 
btw we can make a meeting where we can make some 'rules' about some validations like strings should have a max length of 191 and etc.

**Comment by Dzalevski** [comment]
@FilipNikolovski 
`params := &postTemplate{}
	if err := c.ShouldBind(params); err != nil {
		for _, fieldErr := range err.(validator.ValidationErrors) {
			c.JSON(http.StatusBadRequest, gin.H{
				"message": fmt.Sprintf("Invalid parameter %s, failed on validation: %s", strings.ToLower(fieldErr.Field()), strings.ToLower(fieldErr.ActualTag())),
			})
			return
		}
	}`

**Comment by Dzalevski** [comment]
@FilipNikolovski response: 
``` json 
{
  "message": "Invalid parameter  name, failed on validation: required "
} ```

**Comment by Gligor23** [comment]
@FilipNikolovski @Dzalevski we need to talk about validating fields with `validator` and `gin`. It's a little bit complicated to return user friendly messages to the user for failed validatons.

**Comment by Dzalevski** [comment]
@FilipNikolovski  We have tried there is 2 pull requests but just like @Gligor23 said, messages are  little bit confusing.

**Comment by Dzalevski** [comment]
Spent 3h on this issue with @Gligor23

**Comment by Dzalevski** [comment]
3h+4h= 7hTotal.

**Comment by Gligor23** [comment]
@FilipNikolovski i spent some time validating and i found problem to validate strings with all leading and trailing white spaces. Possible solution that we came out with @Dzalevski is if we just bind params then trim them and then validate, do you agree with that?

**Comment by Gligor23** [comment]
spent 4h yesterday and 3h today so far

**Comment by FilipNikolovski** [comment]
@Gligor23 That's a good catch. Can you give an example of the solution?

**Comment by Gligor23** [comment]
First we bind the data and validate it (trailing spaces can pass this validation also)
```go
package actions

type postSESKeysParam struct {
	AccessKey string `form:"access_key" binding:"required,alphanum"`
	SecretKey string `form:"secret_key" binding:"required"`
	Region    string `form:"region" binding:"required"`
}

func PostSESKeys(c *gin.Context) {
	u := middleware.GetUser(c)

	_, err := storage.GetSesKeys(c, u.ID)
	if err == nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"message": "AWS Ses keys are already set.",
		})
		return
	}

	params := &postSESKeysParam{}
	if err := c.ShouldBind(params); err != nil {
		AbortWithError(c, err)
		return
	}

	keys := &entities.SesKeys{
		AccessKey: strings.TrimSpace(params.AccessKey),
		SecretKey: strings.TrimSpace(params.SecretKey),
		Region:    strings.TrimSpace(params.Region),
		UserID:    u.ID,
	}

        fieldErr, valid := keys.Validate(validator.New())
	if !valid {
		c.JSON(http.StatusBadRequest, gin.H{
			"message": fieldErr.Error(),
		})
		return
	}

	sender, err := emails.NewSesSender(keys.AccessKey, keys.SecretKey, keys.Region)
	if err != nil {
		logger.From(c).WithError(err).Warn("Unable to create SES sender.")
		c.JSON(http.StatusBadRequest, gin.H{
			"message": "SES keys are incorrect.",
		})
		return
	}

	snsClient, err := events.NewEventsClient(keys.AccessKey, keys.SecretKey, keys.Region)
	if err != nil {
		logger.From(c).WithError(err).Warn("Unable to create SNS client.")
		c.JSON(http.StatusBadRequest, gin.H{
			"message": "SES keys are incorrect.",
		})
		return
	}

	//TODO: Move this to work queue to be more robust.
	//createAWSResources is a slow process and could fail periodically.
	go func(
		c *gin.Context,
		sender emails.Sender,
		snsClient events.EventsClient,
		keys *entities.SesKeys,
		uuid string,
	) {
		err := createAWSResources(sender, snsClient, uuid)
		if err != nil {
			logger.From(c).WithError(err).Warn("Unable to create AWS resources.")
			return
		}

		err = storage.CreateSesKeys(c, keys)
		if err != nil {
			logger.From(c).WithError(err).Warn("Unable to create SES keys.")
		}
	}(c.Copy(), sender, snsClient, keys, u.UUID)

	c.JSON(http.StatusOK, gin.H{
		"message": "We are currently processing the request.",
	})
}
```
Validate keys struct after trim spacing the parameters
```go
package entities

// SesKeys entity holds information about the client's
// SES access and secret key.
type SesKeys struct {
	ID        int64     `json:"id" gorm:"column:id; primary_key:yes"`
	UserID    int64     `json:"-" gorm:"column:user_id; index"`
	AccessKey string    `json:"access_key" gorm:"not null" validate:"required,alphanum"`
	SecretKey string    `json:"secret_key,omitempty" gorm:"not null" validate:"required"`
	Region    string    `json:"region" gorm:"not null" validate:"required"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Errors map[string]string `json:"-" sql:"-"`
}

// Validate campaign properties,
func (s *SesKeys) Validate(v *validator.Validate) (fieldErr validator2.FieldError, valid bool) {
	// Validate the instance
	if err := v.Struct(s); err != nil {
		for _, fe := range err.(validator.ValidationErrors) {
			fieldErr.Err =  fe
		}
		return fieldErr, false
	}

	return fieldErr, true
}
```
Also we can implement error interface on our filed error instead of stringer
```go
package validator

type FieldError struct {
	Err validator.FieldError
}

func (q FieldError) Error() string {
	var sb strings.Builder

	sb.WriteString("Validation failed on field '" + q.Err.Field() + "'")
	sb.WriteString(", condition: " + q.Err.ActualTag())

	// Print condition parameters, e.g. max=191 -> max { 191 }
	if q.Err.Param() != "" {
		sb.WriteString(" " + q.Err.Param())
	}

	return sb.String()
}
```
It is kind a double validation but we can also remove the validation on binding.
Also we should make our default validator to be singleton struct or we should put it in the context so we can use the same validtor in every action (that means refactor to the action above).

@FilipNikolovski @Dzalevski

**Comment by FilipNikolovski** [comment]
We could validate the struct separately instead of doing it in ShouldBind. We can still use ShouldBind, but only for binding the parameters to the struct and then use Validate to validate the struct separately.

I don't like the idea of using validate inside an entity struct, we should use it in the request param structs. Let's further discuss this on discord later on.

**Comment by Gligor23** [comment]
@FilipNikolovski @Dzalevski Can we make a call around 7pm today?

**Comment by FilipNikolovski** [comment]
I'm available.

**Comment by Gligor23** [comment]
Spent 2h today on this issue

**Comment by Gligor23** [comment]
Spent 2h today

**Comment by Dzalevski** [comment]
1h.

**Comment by Gligor23** [comment]
1h yesterday 1h today

**Comment by Dzalevski** [comment]
3h today for now. (edit later if i work more)

**Comment by Gligor23** [comment]
Spent 2h 30m today

**Comment by Dzalevski** [comment]
1h today. edit later.

**Comment by Gligor23** [comment]
spent 3h today
