### ISSUE TITLE
Export subscribers

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#541]
**Is your feature request related to a problem? Please describe.**
We need a way of exporting subscribers in a CSV file.

**Describe the solution you'd like**
We'll need an endpoint that will start the export process and send the CSV file to an S3 bucket. After the process is finished
the user will receive a pre-signed S3 URL so that he can use it to download the file directly.

Since the export process is a lengthy one, we'll do it in a separate goroutine (or maybe another consumer) and immediately send a response back to the user. When the process is done, we'll notify the user to download his file (which will be located in the reports UI section).

We can keep a list of all exports and present them to our user in a list, so he can choose which file he downloads. When the user chooses a file to download, we'll need to pre-sign the S3 URL and send it back to the user so he can use it in order to download the file.

**Additional context**
I think that we'll need two or maybe three endpoints for this feature:
1. Export subscribers endpoint (creates & uploads a CSV file to S3)
2. List all subscriber export reports.
3. Sign S3 url used for download.

**Comment by FilipNikolovski** [comment]
Reports table:
- id
- user_id
- resource
- filename
- type (export, import)
- status (in_progress, done, failed)
- note
- created_at
- updated_at

**Comment by Dzalevski** [comment]
3h.

**Comment by Dzalevski** [comment]
1h 30m

**Comment by Gligor23** [comment]
We can have `Export` interface
```go
type Exporter interface {
    Execute()
    // maybe methods for reports table or smth else i cant tell right now
}

func  NewExporter() Exporter {
}
```
Then we can have different exporter for each resource who will implement the Exporter interface, smth like this
```go
type SubscriptionExporter struct {
}

func NewSubscriptionExporter(){

}

func (se *SubscriptionsExporter) Execute () {

}
```
Then the constructor for the exporter would look like
```go
func  NewExporter(resource string) Exporter {
    switch resource {
        case "subscriptions":
            return NewSubscriptionExporter()
    }
}
```
The endpoint will look like
```/api/export:resource```
```go
func ExportSubscribers(c *gin.Context) {
    // do validation

   // insert in report table

  exporter := NewExporter(resource)

   go Execute()

   // return response
}
```
So if we need another resource export we wil ljust add another exporter struct, implement the exporter interface and thats it.

**Comment by FilipNikolovski** [comment]
This is a step in the right direction. I'm thinking we should have an Exporter service, that will do the checks (in progress, limit, etc.) and will have a specific exporter as a dependency that will do the export functionality.

That way we can re-use the code for the checks and uploading the file to s3.

But I think we should have a separate endpoint for each resource, it's better if we do it like `/api/subscribers/export` instead of the other way around. One endpoint could end up with too much complexity.

Also, for the naming of the methods, if we have an Exporter interface, the method name should be naturally `Export`..`Execute` is too ambiguous, i don't like that name.

**Comment by Gligor23** [comment]
3h

**Comment by Gligor23** [comment]
Also i think maybe we should create `ReportService` 
```go
type SubscriptionExporter struct {
}

func NewSubscriptionExporter(){
}

func (se *SubscriptionsExporter) Export (c *gin.Context) {
}
```
```go
type Exporter interface {
    Export(c *gin.Context)
}

func  NewExporter(resource string) Exporter {
    switch resource {
        case "subscriptions":
            return NewSubscriptionExporter()
    }
}
```
```go
type ReportService interface {
    // this do method will create report and start execute in a go routine
    Export(c *gin.Context, exporter Exporter, userID int64, resource, filename, note string, createdAt time.Time) (*Report, error)
    GetReportStatus(reportID int64) (string, error)
}
```
Then we can add `Importer` and ad `Import` method in `ReportService`. Same implementation as `Exporter`.

**Comment by FilipNikolovski** [comment]
Let's gather our thoughts a bit here. Okay, so far we'll need something like this:

1. A report service that will contain the generic functionality around creating a report, which are:
    - Check if another report is already `in_progress`
    - Check the resource limit on generating the report
    - Create a report record and set it `in_progress`
    - Create the actual CSV report with a specific `exporter`
    - Update the report to either `done` or `failed` and set a note
2. Endpoint that will start the report export
3. Endpoint that will check for status of report and return a pre-signed URL.

The Exporter interface should have one method as @Gligor23 said:

```go
Export(userID int64) error // we can add more arguments later on
```

And the ReportService can have the exporter as a dependency, something like this:

```go
type ReportService struct {
  exporter Exporter
}
```

The method for generating the report can be named like `GenerateReport` or something along those lines, and have the resource name and user id as arguments. The rest of the arguments are not needed.

The filename can be named based on the resource and a timestamp:

```
/reports/{user_id}/subscribers_123456.csv
```

**Comment by Dzalevski** [comment]
3h30m.

**Comment by Gligor23** [comment]
3h

**Comment by Dzalevski** [comment]
1h

**Comment by Gligor23** [comment]
1h

**Comment by Dzalevski** [comment]
2h.

**Comment by Gligor23** [comment]
3h 30m

**Comment by Dzalevski** [comment]
1h

**Comment by Gligor23** [comment]
4h 30m

**Comment by Gligor23** [comment]
2h

**Comment by Gligor23** [comment]
2h

**Comment by Gligor23** [comment]
2h

**Comment by Dzalevski** [comment]
3h.

**Comment by Gligor23** [comment]
1h
