### ISSUE TITLE
Campaign stats: clicks endpoint

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#719]
API endpoint

GET /api/campaigns/{id}/clicks

Response object
```json
{
  "total": 123,
  "collection": [
    {
       "link": "http://example.com?foo=bar",
       "unique_clicks": 123,
       "total_clicks": 456
    },
    ...
  ]
}
```

**Comment by Gligor23** [comment]
@FilipNikolovski does`total` in the response represents total links for the campaign?

**Comment by FilipNikolovski** [comment]
@Gligor23 total should represent the size of the collection.

**Comment by Gligor23** [comment]
Spent 3h on this issue last two days

**Comment by Gligor23** [comment]
Spent 2h 30m on this issue today
