### ISSUE TITLE
Action handlers tests

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#820]
**Is your feature request related to a problem? Please describe.**
We'll need a way of testing our action handlers. In this issue, we'll discuss and propose a solution.

**Describe the solution you'd like**
Choose a framework for testing our HTTP handlers and make one test that will serve as a blueprint for all future tests. Proposed frameworks are:
1. [httpexpect](https://github.com/gavv/httpexpect)
2. [Ginkgo](https://onsi.github.io/ginkgo/)
3. [testify](https://github.com/stretchr/testify)

**Comment by Dzalevski** [comment]
1h.

**Comment by Dzalevski** [comment]
2h.

**Comment by Dzalevski** [comment]
2h.

**Comment by Dzalevski** [comment]
3h(subscriptions tests  + subs collection filter)

**Comment by Gligor23** [comment]
1h

**Comment by Dzalevski** [comment]
1h

**Comment by Gligor23** [comment]
1h

**Comment by Dzalevski** [comment]
1h

**Comment by Gligor23** [comment]
1h

**Comment by gudgl** [comment]
2h

**Comment by gudgl** [comment]
3h

**Comment by gudgl** [comment]
2h
