### ISSUE TITLE
Refactor campaigns to use the new template resource

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#952]
Currently the `campaign` resource stores the template name in it's storage. After the templates refactor, the campaigns table should replace the template name with a foreign key to the templates table. The `create` and `update` operation will remain the same from the API perspective. Since the template name will be a unique value, we can search for the template by name and fetch the id and use that value when we create or update a campaign.

The `get` and `list` endpoints will be changed, to include a `template` object, instead of just the template name.
It should look something like this:

```json
{
  "id": 123,
  "name": "Campaign Foo",
  "status": "draft",
  "template": {
    "id": 456,
    "name": "Foo",
    "subject": "Hello {{name}}",
    "created_at": "2020-12-17T12:00:0000",
    "updated_at": "2020-12-17T12:00:0000",
  },
   "created_at": "2020-12-17T12:00:0000",
   "updated_at": "2020-12-17T12:00:0000",  
}
```

Here are the steps we should take:
1. Remove `template_name` column
2. Add `template_id` as a foreign key column
3. Refactor Create and Update endpoints to fetch template by name and store the id in the campaign record.
4. Refactor Get and List to include `template` sub-object.

**Comment by Dzalevski** [comment]
1h

**Comment by Dzalevski** [comment]
2h

**Comment by gudgl** [comment]
@FilipNikolovski what about the text part and the html part shouldn't they be also included in the response on get category?

**Comment by gudgl** [comment]
1h

**Comment by FilipNikolovski** [comment]
> @FilipNikolovski what about the text part and the html part shouldn't they be also included in the response on get category?

As we discussed, we won't need the text and html part for the **get campaign** endpoint.
