### ISSUE TITLE
New "sender" consumer to handle SendEmail AWS action (send email to a subscriber)

### ISSUE THREAD

**Issue by FilipNikolovski** [mailbadger/app#995]
Draft design of the flow:

![sender](https://user-images.githubusercontent.com/35736870/104511624-4baa6380-55ed-11eb-88ea-dd704a8f3fc0.png)

Update the image if there are any changes, and add retries on this [link](https://excalidraw.com/#json=4698154893049856,jSbWjut3PaniwU5N3W4DpQ)

The **sender** consumer will have the task to send an email using the SendEmail AWS action. The message that is sent to this channel will contain all of the necessary information required to send an email - a destination email, from email, message, user's ses keys, and a unique id (for idempotency purposes).

After a successful send, we store the message in the log along with the message ID.

The consumer needs to handle idempotency (duplicate messages should be dropped) in order to avoid sending an email multiple times to a subscriber.

**Comment by gudgl** [comment]
@FilipNikolovski can you confirm that this is our case for sending mails https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ses-example-send-email.html

**Comment by gudgl** [comment]
1h

**Comment by FilipNikolovski** [comment]
> @FilipNikolovski can you confirm that this is our case for sending mails https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ses-example-send-email.html

Yes this is the one, we also need to add the `ConfigurationSetName` in the params and I think that's it.

**Comment by gudgl** [comment]
3h

**Comment by gudgl** [comment]
Update version of sender flow

![sender](https://user-images.githubusercontent.com/35736870/106308339-da131c00-6260-11eb-8901-975fab4b10d2.png)

**Comment by gudgl** [comment]
4h

**Comment by gudgl** [comment]
1h

**Comment by gudgl** [comment]
1h (yesterday + today)
